version: '3'
services:
  first:
    image: nginx
    ports:
      - "8080:80"
      - "4433:443"
    environment:
      - NGINX_PORT=80
    volumes:
      - ./first/html:/usr/share/nginx/html
      - ./first/ssl/:/etc/nginx/ssl
      - ./first/conf.d/ssl.conf:/etc/nginx/conf.d/ssl.conf
  third:
    image: nginx
    ports:
      - "8090:80"
      - "4443:443"
    environment:
      - NGINX_PORT=80
    volumes:
      - ./third/html:/usr/share/nginx/html
      - ./third/ssl/:/etc/nginx/ssl
      - ./third/conf.d/ssl.conf:/etc/nginx/conf.d/ssl.conf
