version: '3'
services:
  first:
    image: nginx
    ports:
      - "8080:80"
    environment:
      - NGINX_PORT=80
    volumes:
      - ./first/html:/usr/share/nginx/html
  third:
    image: nginx
    ports:
      - "8081:80"
    environment:
      - NGINX_PORT=80
    volumes:
      - /third/html:/usr/share/nginx/html

